name: Generate Maps

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of maps to generate'
        required: true
        default: 'all'
        type: choice
        options:
          - 'all'
          - 'extreme'
          - 'stupid'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: |
          pip install -r requirements.txt
          echo "RUN_TYPE=${{ github.event.inputs.type || 'extreme' }}" >> $GITHUB_ENV
          echo "CURRENT_DATE=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Generate OBS_EXT
        if: ${{ env.RUN_TYPE == 'all' || env.RUN_TYPE == 'extreme' }}
        run: |
          bash run_extreme.sh >> message.txt
          mv generated_extreme obs_extreme-${CURRENT_DATE}
          tar -czf obs_extreme-${CURRENT_DATE}.tar.gz obs_extreme-${CURRENT_DATE}

      - name: Generate OBS_STUPID
        if : ${{ env.RUN_TYPE == 'all' || env.RUN_TYPE == 'stupid' }}
        run: |
          bash run_stupid.sh >> message.txt
          mv generated_stupid obs_stupid-${CURRENT_DATE}
          tar -czf obs_stupid-${CURRENT_DATE}.tar.gz obs_stupid-${CURRENT_DATE}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.CURRENT_DATE }}
          tag_name: ${{ env.CURRENT_DATE }}
          body_path: message.txt
          files: |
            *.tar.gz
